# Generated by Django 5.1.4 on 2025-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user42',
            name='email_address',
            field=models.EmailField(default='placeholder@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user42',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='user42',
            name='password',
            field=models.CharField(default='to_be_hashed', max_length=128),
        ),
    ]
