# Generated by Django 4.2 on 2025-02-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0003_user42_is_2fa_enabled_user42_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user42',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
