# Generated by Django 4.2 on 2025-02-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0004_alter_user42_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user42',
            name='profile_image',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
