# Generated by Django 4.2.19 on 2025-02-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0005_user42_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user42',
            name='profile_image',
            field=models.ImageField(default='profile_pictures/default_avatar.png', upload_to='profile_pictures/'),
        ),
    ]
