# Generated by Django 4.2 on 2025-02-17 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0005_user42_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user42',
            name='profile_image',
            field=models.ImageField(default='profile_pictures/default_avatar.png', upload_to='profile_pictures/'),
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_app.user42')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
