# Generated by Django 4.2 on 2025-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0006_alter_user42_profile_image_userloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginhistory',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
