# Generated by Django 4.2 on 2025-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0007_userloginhistory_is_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user42',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
