# Generated by Django 4.2 on 2025-03-21 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(default=2)),
                ('score_limit', models.PositiveIntegerField(default=5)),
                ('lives', models.PositiveIntegerField(default=3)),
                ('ball_speed', models.PositiveIntegerField(default=7)),
                ('map_choice', models.CharField(default='retro', max_length=30)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='game_settings', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
        ),
    ]
